### ISSUE TITLE
Explore the Categories of apps

### ISSUE THREAD

**Issue by shreyanshbehani** [mishra-atul5001/Data-Science-Medium-Content#18]
Take top 5 categories and explore top 5 apps for all these categories based on Installs and Ratings

**Comment by mishra-atul5001** [comment]
Top 5 apps from each categories needs WORDCLOUD and sentiment distribution in pie chart

**Comment by mishra-atul5001** [comment]
Hi @shreyanshbehani ,

Please provide 5 more apps to review.
