### ISSUE TITLE
Remaining 5 APPS to be explored by Shreyansh.

### ISSUE THREAD

**Issue by mishra-atul5001** [mishra-atul5001/Data-Science-Medium-Content#5]
Hi Shreyansh,

Please look at the ipynb file for the [top 10 Apps.](https://github.com/mishra-atul5001/Data-Science-Medium-Content/issues/3#issuecomment-696153819)

**Comment by mishra-atul5001** [comment]
Hi Shreyansh,

Below are the Apps for you as part of your task: 

**Five Nights at Freddy's
Messenger – Text and Video Chat for Free
Subway Surfers
PUBG MOBILE
PayPal**

**Comment by mishra-atul5001** [comment]
Any Update @shreyanshbehani ?

**Comment by shreyanshbehani** [comment]
Starting with code.

**Comment by shreyanshbehani** [comment]
Reviews data set doesn't have any information of the 5 apps assigned to me

**Comment by mishra-atul5001** [comment]
Hi @shreyanshbehani , could you please provide the same as evidence in a **Jupyter Notebook**.

**Comment by mishra-atul5001** [comment]
Hi @shreyanshbehani ,

Out of the 10 Apps, only GMAIL reviews are present. Kindly refer to the below attachment.

![image](https://user-images.githubusercontent.com/22134737/94515049-5c9eb700-0240-11eb-8448-8c6f5bb9b4f5.png)

Till Now, we have **Amazon Shopping and Gmail** reviews only!. Let's discuss more in today's standup.
